// <auto-generated />
namespace Ticket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Assignment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Assignment));
        
        string IMigrationMetadata.Id
        {
            get { return "202008281657187_Assignment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
